### ISSUE TITLE
Code outside of project used as a type root

### ISSUE THREAD

**Issue by gloomybrain** [ringcentral/testring#44]
See this: https://github.com/ringcentral/testring/blob/fa70b48dc899726e9e8d2ec0b564f54068c9f310/tsconfig.json#L23
And this:
https://github.com/ringcentral/testring/blob/fa70b48dc899726e9e8d2ec0b564f54068c9f310/tsconfig.json#L36

Both of these lines refer to somewhere outside of the project folder, which looks at least wrong and probably dangerous.

**Comment by johnthecat** [comment]
Hi! This line was added, because we create symlink to `tsconfig.json` for every package (`testring/packages/package-name/tsconfig.json`). So this path refers to the root of project.
Do you have any ideas how can we fix this?

**Comment by gloomybrain** [comment]
Frankly speaking I haven't been able to see any of the symlinks you are talking about in the sources (I'd quickly flipped through a couple of packages) so it seems that these symlinks are generated in build-time, right? This is still an open question whether or not to copy the `tsconfig.json` file or to create a symlink during the build process, so I'd prefer to put it aside this time.

Whatsoever regarding the fix what I would like to propose is to:
a) have a separate `tsconfig.json` file in each typescript package
b) use `extend` configuration key [described here](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) in order to avoid code duplication

**Comment by flops** [comment]
This proposal got its pros and cons.

Pros are that you can setup typescript compiler for every package independent when you need.
Cons are actually the same in my mind, i'd like project to use the same ts\es6 features. It makes code more readable and similar code style for all packages.
So i have some doubts.

**Comment by flops** [comment]
Closing this issue as i don't see real need for that. But if we will need specific build for every package i will add it under that issue.
